export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST='REGISTER_REQUEST';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAILURE='REGISTER_FAILURE';

export const ADD_REMINDER_SUCCESS = 'ADD_REMINDER_SUCCESS';
export const ADD_REMINDER_FAILURE = 'ADD_REMINDER_FAILURE';

export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';

export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS';
export const UPDATE_REMINDER_FAILURE = 'UPDATE_REMINDER_FAILURE';

export const GET_REMINDER_SUCCESS = 'GET_REMINDER_SUCCESS';
export const GET_REMINDER_FAILURE = 'GET_REMINDER_FAILURE';

